[package]
name = "bevy-trait-query"
version = "0.4.0-dev"
edition = "2021"

description = "Implementation of trait queries for the bevy game engine"
repository = "https://github.com/JoJoJet/bevy-trait-query/"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "gamedev", "plugin", "query", "trait"]
categories = ["game-development"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bevy_app", "bevy_core"]

[dependencies]
bevy-trait-query-impl = { path = "proc-macro", version = "0.4.0-dev" }
tracing = "0.1"

[dependencies.bevy_ecs]
git = "https://github.com/bevyengine/bevy"
rev = "060711669903306c59eaea427498948992f0e768"

[dependencies.bevy_app]
git = "https://github.com/bevyengine/bevy"
rev = "060711669903306c59eaea427498948992f0e768"
optional = true

[dependencies.bevy_core]
git = "https://github.com/bevyengine/bevy"
rev = "060711669903306c59eaea427498948992f0e768"
optional = true

[dev-dependencies]
criterion = "0.5"

[dev-dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "060711669903306c59eaea427498948992f0e768"
default-features = false

[[bench]]
name = "concrete"
harness = false

[[bench]]
name = "all"
harness = false

[[bench]]
name = "one"
harness = false

[[bench]]
name = "fragmented"
harness = false
