[package]
name = "bevy-trait-query"
version = "0.1.0-dev"
edition = "2021"

description = "Implementation of trait queries for the bevy game engine"
repository = "https://github.com/JoJoJet/bevy-trait-query/"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "gamedev", "plugin", "query", "trait"]
categories = ["game-development"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy-trait-query-impl = { path = "proc-macro" }

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "ea4aeff9ec8e204b8d4bc8cbb10c28e90fe271ff"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "concrete"
harness = false

[[bench]]
name = "all"
harness = false

[[bench]]
name = "one"
harness = false

[[bench]]
name = "fragmented"
harness = false
